name: my_website
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  screen_go: ^1.1.8

  # localization الرسمي من Flutter (لـ Material و Widgets و Cupertino)
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  riverpod_annotation: ^3.0.3
  shared_preferences_web: ^2.4.3
  seo_renderer: ^0.6.0
  cached_network_image: ^3.4.1
  dotted_line: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.3.0
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  # ✅ ضروري عشان Flutter يولّد ملفات AppLocalizations
  generate: true

  assets:
  - assets/images/
  - assets/fonts/
  - assets/icons/svg/
  - assets/images/backgrounds/
  - assets/video/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: IRANYekan
      fonts:
        - asset: "assets/fonts/Qs_Iranyekan thin.ttf"
          weight: 100
        - asset: "assets/fonts/Qs_Iranyekan light.ttf"
          weight: 300
        - asset: "assets/fonts/Qs_Iranyekan medium.ttf"
          weight: 500
        - asset: "assets/fonts/Qs_Iranyekan bold.ttf"
          weight: 700
        - asset: "assets/fonts/Qs_Iranyekan extrabold.ttf"
          weight: 800
        - asset: "assets/fonts/Qs_Iranyekan extrablack.ttf"
          weight: 900
